// <auto-generated />
namespace DataAccesLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migupdateslidertexttitle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migupdateslidertexttitle));
        
        string IMigrationMetadata.Id
        {
            get { return "202112110842044_mig-update-slidertexttitle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
