// <auto-generated />
namespace DataAccesLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migupdatesliderbutonway : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migupdatesliderbutonway));
        
        string IMigrationMetadata.Id
        {
            get { return "202112081359274_mig-update-slider-buton-way"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
